name: clean_architecture_template
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0+4
  bloc: ^3.0.0
  flutter_bloc: ^3.2.0
  mockito: ^4.1.1
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  dartz: ^0.8.9
  get_it: ^4.0.1
  equatable: ^1.1.1
  cross_connectivity: ^1.0.0
  universal_platform: ^0.1.3
  dio: ^3.0.9
  rxdart: ^0.23.1
  cupertino_icons: ^0.1.3

dependency_overrides:
  path: 1.7.0
  quiver: 2.0.3
  rxdart: ^0.23.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^0.7.0+2
  build_runner: ^1.10.0


flutter:

  uses-material-design: true
