name: clean_architecture_template
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.2
  bloc: ^6.0.3
  flutter_bloc: ^6.0.1
  mockito: ^4.1.1
  hive: ^1.4.2
  hive_flutter: ^0.3.1
  dartz: ^0.9.1
  get_it: ^4.0.4
  equatable: ^1.2.3
  cross_connectivity: ^1.0.2
  universal_platform: ^0.1.3
  dio: ^3.0.9
  #rxdart: ^0.24.1
  cupertino_icons: ^0.1.3

dependency_overrides:
  #path: 1.7.0
  #quiver: 2.0.3
  #rxdart: ^0.24.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^0.7.1
  build_runner: ^1.10.0


flutter:

  uses-material-design: true
